#!/bin/bash
# Fix Samba to allow simple binds without TLS (test environment only)
set -e

# Find the smb.conf generated by samba-tool provision
SMBCONF=$(find /etc/samba /var/lib/samba -name "smb.conf" 2>/dev/null | head -1)
echo "Found smb.conf at: $SMBCONF"

# Check if setting already exists
if grep -q "ldap server require strong auth" "$SMBCONF" 2>/dev/null; then
    echo "Setting already exists, updating..."
    sed -i 's/ldap server require strong auth.*/ldap server require strong auth = no/' "$SMBCONF"
else
    echo "Adding setting to [global] section..."
    sed -i '/^\[global\]/a\\tldap server require strong auth = no' "$SMBCONF"
fi

echo "Current smb.conf [global] section:"
head -20 "$SMBCONF"

echo ""
echo "Restarting Samba AD DC..."
systemctl restart samba-ad-dc
sleep 3

echo ""
echo "Testing LDAP bind..."
ldapsearch -H ldap://localhost -x -D "CN=svc-onyx-ldap,OU=ServiceAccounts,DC=onyx,DC=local" -w "SvcOnyxLDAP2026!" -b "DC=onyx,DC=local" "(&(objectClass=person)(mail=*))" cn mail -LLL 2>&1 | head -30

echo ""
echo "=== FIX COMPLETE ==="
